config/routes.rb
Rails.application.routes.draw do
  resources :targetdatabases
  resources :sourcedatabases

root 'welcome#home'
get 'welcome/home', to: 'welcome#home'

end

app/models/sourcedatabase.rb
class Sourcedatabase < ActiveRecord::Base
    belongs_to :user    
   validates :DBName, presence: true , length: { minimum: 3, maximum:50}
   validates :user_id, presence: true
end

app/models/targetdatabase.rb
class Targetdatabase < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sourcedatabases
  before_save {self.email = email.downcase}
  validates :username, presence: true, uniqueness: true, length: {minimum: 3, maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: {minimum: 3, maximum: 105}, 
                    format: { with: VALID_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sourcedatabases_controller.rb
class SourcedatabasesController < ApplicationController

before_action :set_sourcedatabase, only: [:edit, :update, :show, :destroy]

def destroy
 @sourcedatabase.destroy
 flash[:notice] = "Source Database was successfully deleted"
 redirect_to sourcedatabases_path
 
end

    def new
        @sourcedatabase = Sourcedatabase.new
    end
    
    def index
        @sourcedatabases = Sourcedatabase.all
    end
    
    def edit
    end
    
    def update

        if @sourcedatabase.update(sourcedatabase_params)
            flash[:notice] = "Source Database details successfully updated"
            redirect_to sourcedatabase_path(@sourcedatabase)    
        else
            render 'edit'
        end
    end
    def create
        #render plain: params[:sourcedatabase].inspect
       @sourcedatabase = Sourcedatabase.new(sourcedatabase_params)
       @sourcedatabase.user = User.first    
       if @sourcedatabase.save
           flash[:notice] = "Sourcedatabase was successfully created"
           redirect_to sourcedatabase_path(@sourcedatabase)
        else
           render 'new' 
        end
           
    end
    
    def show
    end
    
    private
    def sourcedatabase_params
        params.require(:sourcedatabase).permit(:DBName,:Engine, :MasterUser,:MasterUserPassword,:Server,:Port
        
        
        )
    end
    
    private 
    def set_sourcedatabase
        @sourcedatabase = Sourcedatabase.find(params[:id])
    end
end

app/controllers/targetdatabases_controller.rb
class TargetdatabasesController < ApplicationController
  before_action :set_targetdatabase, only: [:show, :edit, :update, :destroy]

  # GET /targetdatabases
  # GET /targetdatabases.json
  def index
    @targetdatabases = Targetdatabase.all
  end

  # GET /targetdatabases/1
  # GET /targetdatabases/1.json
  def show
  end

  # GET /targetdatabases/new
  def new
    @targetdatabase = Targetdatabase.new
  end

  # GET /targetdatabases/1/edit
  def edit
  end

  # POST /targetdatabases
  # POST /targetdatabases.json
  def create
    @targetdatabase = Targetdatabase.new(targetdatabase_params)

    respond_to do |format|
      if @targetdatabase.save
        format.html { redirect_to @targetdatabase, notice: 'Targetdatabase was successfully created.' }
        format.json { render :show, status: :created, location: @targetdatabase }
      else
        format.html { render :new }
        format.json { render json: @targetdatabase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targetdatabases/1
  # PATCH/PUT /targetdatabases/1.json
  def update
    respond_to do |format|
      if @targetdatabase.update(targetdatabase_params)
        format.html { redirect_to @targetdatabase, notice: 'Targetdatabase was successfully updated.' }
        format.json { render :show, status: :ok, location: @targetdatabase }
      else
        format.html { render :edit }
        format.json { render json: @targetdatabase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targetdatabases/1
  # DELETE /targetdatabases/1.json
  def destroy
    @targetdatabase.destroy
    respond_to do |format|
      format.html { redirect_to targetdatabases_url, notice: 'Targetdatabase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_targetdatabase
      @targetdatabase = Targetdatabase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def targetdatabase_params
      params.fetch(:targetdatabase, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
def home
    
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/targetdatabases_helper.rb
module TargetdatabasesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer"> 
   <small>
Copyright © <a href="enter in a link here">InSync Cloud</a>

by <a href="#">Adam Gladstone</a>
   </small>
  <nav>
   <ul>
     <li><%= link_to "Home", root_path %></li>
   </ul>
   </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
  <ul>
    <li>
      <%= msg %>
    </li>
  </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Insync Cloud", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Sourcedatabases", sourcedatabases_path %> </li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Sourcedatabase", new_sourcedatabase_path %> </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Sourcedatabase", new_sourcedatabase_path %> </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Insync</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div  class="container">
   <%= yield %>
</div>
</body>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</html>

app/views/sourcedatabases/_form.html.erb
<% if @sourcedatabase.errors.any? %>
<h2>
    The following errors prevented the records from creating
</h2>
<ul>
    <% @sourcedatabase.errors.full_messages.each do |msg| %>
    <li>
        <%= msg %>
    </li>
        <% end %>    
</ul>
        <% end %>    

<%= form_for @sourcedatabase do |f| %>
<p>
    <%=f.label :DBName %> 
    <%=f.text_field :DBName %>    <br/>
        <%=f.label :Engine %> 
    <%=f.text_field :Engine %>    <br/>
        <%=f.label :MasterUser %> 
    <%=f.text_field :MasterUser %>    <br/>
        <%=f.label :MasterUserPassword %> 
    <%=f.text_field :MasterUserPassword %> <br/>   
        <%=f.label :Server %> 
    <%=f.text_field :Server %>    <br/>
        <%=f.label :Port %> 
    <%=f.text_field :Port %>    
</p>
<p>
    <%= f.submit %>

</p>
<% end %>    

app/views/sourcedatabases/edit.html.erb
<h1> Edit Source Database</h1>

<%= render 'form' %>

app/views/sourcedatabases/index.html.erb
<h1>Listing all source databases</h1>

<p> <%= link_to "Create new Source Database", new_sourcedatabase_path %> </p>

<table>
    <tr>
        <th>DBName</th>
        <th>Engine</th>
        <th>MasterUser</th>
        <th>MasterUserPassword</th>
        <th>Server</th>
        <th>Port</th>
    </tr>
    
<% @sourcedatabases.each do |sourcedatabase| %>
        <tr>
        <td> <%= sourcedatabase.DBName %> </td>
        <td> <%= sourcedatabase.Engine %> </td>
        <td> <%= sourcedatabase.MasterUser %> </td>
        <td> <%= sourcedatabase.MasterUserPassword %> </td>
        <td> <%= sourcedatabase.Server %> </td>
        <td> <%= sourcedatabase.Port %> </td>
        <td> <%= link_to 'Edit', edit_sourcedatabase_path(sourcedatabase) %> </td>
        <td> <%= link_to 'Show', sourcedatabase_path(sourcedatabase) %> </td>
        <td> <%= link_to 'Delete', sourcedatabase_path(sourcedatabase), method: :delete, data: {confirm: "Are you sure?"} %> </td>
    </tr>

    <% end %>
    </table>

app/views/sourcedatabases/new.html.erb
<h1> Create a new Sourcedatabase</h1>
<%= render 'form' %>

app/views/sourcedatabases/show.html.erb
<h1>
    Showing selected Sourcedatabase
</h1>

<p>    DBName: <%=@sourcedatabase.DBName%></p>    
<p>    Engine: <%=@sourcedatabase.Engine%></p>    
<p> MasterUser: <%=@sourcedatabase.MasterUser%></p>         
<p> MasterUserPassword: <%=@sourcedatabase.MasterUserPassword%> </p>        
<p> Server: <%=@sourcedatabase.Server%></p> 
<p> Port: <%=@sourcedatabase.Port%> </p>    

<%= link_to "Edit this Source Database", edit_sourcedatabase_path(@sourcedatabase) %> |
<%= link_to "Back to Source Database listing", sourcedatabases_path %>

app/views/sourcedatabases/update.html.erb
<h1>
    Updated Source Database Record
</h1>

<% if @sourcedatabase.errors.any? %>
<h2>
    The following errors prevented the records from creating
</h2>
<ul>
    <% @sourcedatabase.errors.full_messages.each do |msg| %>
    <li>
        <%= msg %>
    </li>
        <% end %>    
</ul>
        <% end %>    

<%= form_for @sourcedatabase do |f| %>
<p>
    <%=f.label :DBName %> 
    <%=f.text_field :DBName %>    <br/>
        <%=f.label :Engine %> 
    <%=f.text_field :Engine %>    <br/>
        <%=f.label :MasterUser %> 
    <%=f.text_field :MasterUser %>    <br/>
        <%=f.label :MasterUserPassword %> 
    <%=f.text_field :MasterUserPassword %> <br/>   
        <%=f.label :Server %> 
    <%=f.text_field :Server %>    <br/>
        <%=f.label :Port %> 
    <%=f.text_field :Port %>    
</p>
<p>
    <%= f.submit %>

</p>
<% end %>    

app/views/targetdatabases/_form.html.erb
<%= form_for(@targetdatabase) do |f| %>
  <% if @targetdatabase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@targetdatabase.errors.count, "error") %> prohibited this targetdatabase from being saved:</h2>

      <ul>
      <% @targetdatabase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/targetdatabases/edit.html.erb
<h1>Editing Targetdatabase</h1>

<%= render 'form' %>

<%= link_to 'Show', @targetdatabase %> |
<%= link_to 'Back', targetdatabases_path %>

app/views/targetdatabases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Targetdatabases</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @targetdatabases.each do |targetdatabase| %>
      <tr>
        <td><%= link_to 'Show', targetdatabase %></td>
        <td><%= link_to 'Edit', edit_targetdatabase_path(targetdatabase) %></td>
        <td><%= link_to 'Destroy', targetdatabase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Targetdatabase', new_targetdatabase_path %>

app/views/targetdatabases/new.html.erb
<h1>New Targetdatabase</h1>

<%= render 'form' %>

<%= link_to 'Back', targetdatabases_path %>

app/views/targetdatabases/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_targetdatabase_path(@targetdatabase) %> |
<%= link_to 'Back', targetdatabases_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>InSync Cloud</h1>
<%= link_to "Sign up Now", "#", class: "btn-primary btn-lg"%>
</div>